"""
Quality Evaluation Tool for LLM-Generated Exercises

Helps you manually score and compare the quality of exercises 
generated by different models.

Usage:
    python evaluate_exercise_quality.py --results llm_comparison_results.json
"""

import json
from pathlib import Path
from typing import Dict, List
from dataclasses import dataclass
import sys


@dataclass
class QualityScore:
    """Quality scoring rubric for generated exercises"""
    # Each scored 0-5
    learning_objective_clarity: int = 0  # Is it specific, measurable?
    proof_appropriateness: int = 0  # Does it actually test understanding?
    solution_accuracy: int = 0  # Is the math correct?
    solution_clarity: int = 0  # Is it well-explained?
    misconception_relevance: int = 0  # Is it actually common and helpful?
    difficulty_alignment: int = 0  # Does difficulty match content?
    pedagogical_tone: int = 0  # Is language appropriate for learners?
    
    @property
    def total_score(self) -> int:
        return (
            self.learning_objective_clarity +
            self.proof_appropriateness +
            self.solution_accuracy +
            self.solution_clarity +
            self.misconception_relevance +
            self.difficulty_alignment +
            self.pedagogical_tone
        )
    
    @property
    def max_score(self) -> int:
        return 35  # 7 criteria × 5 points each
    
    @property
    def percentage(self) -> float:
        return (self.total_score / self.max_score) * 100


def display_exercise(model_name: str, transcript_id: str, exercise: Dict, transcript_text: str = None):
    """Display exercise in a readable format"""
    
    print(f"\n{'='*100}")
    print(f"MODEL: {model_name} | VIDEO: {transcript_id}")
    print(f"{'='*100}\n")
    
    if transcript_text:
        print(f"📝 TRANSCRIPT EXCERPT:")
        print(f"{transcript_text[:300]}...\n")
    
    print(f"🎯 LEARNING OBJECTIVE:")
    print(f"   {exercise.get('learning_objective', 'N/A')}\n")
    
    proof = exercise.get('proof_of_learning', {})
    print(f"✅ PROOF OF LEARNING:")
    print(f"   Type: {proof.get('type', 'N/A')}")
    print(f"   Task: {proof.get('task', 'N/A')}")
    print(f"   Success Criteria: {proof.get('success_criteria', 'N/A')}\n")
    
    print(f"📚 WORKED SOLUTION:")
    solution = exercise.get('worked_solution', 'N/A')
    if len(solution) > 500:
        print(f"   {solution[:500]}...")
    else:
        print(f"   {solution}\n")
    
    print(f"⚠️  COMMON MISCONCEPTION:")
    print(f"   {exercise.get('common_misconception', 'N/A')}\n")
    
    print(f"📊 DIFFICULTY: {exercise.get('difficulty_level', 'N/A')}")
    
    visual = exercise.get('visual_spec', {})
    if visual.get('needed'):
        print(f"🖼️  VISUAL: {visual.get('type', 'N/A')} - {visual.get('description', '')}")
    
    print(f"\n{'-'*100}\n")


def prompt_for_scores() -> QualityScore:
    """Interactively prompt user to score an exercise"""
    
    print("\n📊 QUALITY SCORING (0-5 for each criterion):")
    print("   5 = Excellent, 4 = Good, 3 = Acceptable, 2 = Poor, 1 = Very Poor, 0 = Fails")
    print()
    
    scores = QualityScore()
    
    criteria = [
        ("learning_objective_clarity", "Learning Objective Clarity (specific, measurable?)"),
        ("proof_appropriateness", "Proof of Learning (actually tests understanding?)"),
        ("solution_accuracy", "Solution Accuracy (mathematically correct?)"),
        ("solution_clarity", "Solution Clarity (well-explained?)"),
        ("misconception_relevance", "Misconception Relevance (common and helpful?)"),
        ("difficulty_alignment", "Difficulty Alignment (matches content?)"),
        ("pedagogical_tone", "Pedagogical Tone (appropriate for learners?)"),
    ]
    
    for attr, description in criteria:
        while True:
            try:
                score = input(f"   {description}: ")
                if score.lower() in ['s', 'skip']:
                    return None  # User wants to skip
                score = int(score)
                if 0 <= score <= 5:
                    setattr(scores, attr, score)
                    break
                else:
                    print("      Please enter 0-5")
            except ValueError:
                print("      Please enter a number 0-5 (or 's' to skip)")
            except KeyboardInterrupt:
                print("\n\n⚠️  Evaluation interrupted by user")
                return None
    
    print(f"\n   Total Score: {scores.total_score}/{scores.max_score} ({scores.percentage:.1f}%)")
    
    return scores


def evaluate_results(results_path: Path):
    """Main evaluation workflow"""
    
    # Load results
    with open(results_path) as f:
        data = json.load(f)
    
    results = data['results']
    
    print(f"\n{'='*100}")
    print(f"EXERCISE QUALITY EVALUATION")
    print(f"{'='*100}")
    print(f"\nLoaded {len(results)} test results")
    print(f"Models tested: {', '.join(data['test_metadata']['models_tested'])}")
    print(f"\nInstructions:")
    print("  - Review each exercise")
    print("  - Score 0-5 on each criterion")
    print("  - Type 's' to skip an exercise")
    print("  - Press Ctrl+C to exit anytime")
    print()
    
    input("Press Enter to begin evaluation...")
    
    # Group by transcript for side-by-side comparison
    by_transcript = {}
    for result in results:
        tid = result['transcript_id']
        if tid not in by_transcript:
            by_transcript[tid] = []
        by_transcript[tid].append(result)
    
    all_scores = []
    transcript_scores = {}
    
    for transcript_id, transcript_results in by_transcript.items():
        print(f"\n\n{'#'*100}")
        print(f"# TRANSCRIPT: {transcript_id}")
        print(f"# Comparing {len(transcript_results)} models on same content")
        print(f"{'#'*100}\n")
        
        transcript_scores[transcript_id] = {}
        
        for result in transcript_results:
            if result.get('error'):
                print(f"\n❌ {result['model_name']}: ERROR - {result['error']}")
                continue
            
            display_exercise(
                model_name=result['model_name'],
                transcript_id=result['transcript_id'],
                exercise=result['response']
            )
            
            scores = prompt_for_scores()
            
            if scores is None:
                print("\n⏭️  Skipped\n")
                continue
            
            all_scores.append({
                'model': result['model_name'],
                'transcript_id': transcript_id,
                'scores': scores,
                'cost': result['cost'],
                'response_time': result['response_time']
            })
            
            transcript_scores[transcript_id][result['model_name']] = scores
    
    # Generate comparison summary
    print_evaluation_summary(all_scores, transcript_scores)
    
    # Save evaluation results
    output_path = results_path.parent / f"{results_path.stem}_evaluation.json"
    save_evaluation_results(all_scores, output_path)


def print_evaluation_summary(all_scores: List[Dict], transcript_scores: Dict):
    """Print summary of evaluation scores"""
    
    print(f"\n\n{'='*100}")
    print(f"EVALUATION SUMMARY")
    print(f"{'='*100}\n")
    
    # Calculate averages by model
    model_stats = {}
    
    for score_data in all_scores:
        model = score_data['model']
        if model not in model_stats:
            model_stats[model] = {
                'quality_scores': [],
                'costs': [],
                'times': []
            }
        
        model_stats[model]['quality_scores'].append(score_data['scores'].percentage)
        model_stats[model]['costs'].append(score_data['cost'])
        model_stats[model]['times'].append(score_data['response_time'])
    
    # Print table
    print(f"{'Model':<25} {'Avg Quality':<15} {'Avg Cost':<12} {'Avg Time':<12} {'Value Score':<12}")
    print(f"{'-'*100}")
    
    for model, stats in sorted(model_stats.items()):
        avg_quality = sum(stats['quality_scores']) / len(stats['quality_scores'])
        avg_cost = sum(stats['costs']) / len(stats['costs'])
        avg_time = sum(stats['times']) / len(stats['times'])
        
        # Value score: quality per dollar (higher is better)
        value_score = avg_quality / (avg_cost * 1000) if avg_cost > 0 else 0
        
        print(
            f"{model:<25} "
            f"{avg_quality:<14.1f}% "
            f"${avg_cost:<11.6f} "
            f"{avg_time:<11.2f}s "
            f"{value_score:<11.1f}"
        )
    
    print(f"\n{'='*100}\n")
    
    # Winner analysis
    best_quality = max(model_stats.items(), key=lambda x: sum(x[1]['quality_scores']) / len(x[1]['quality_scores']))
    best_value = max(model_stats.items(), key=lambda x: (sum(x[1]['quality_scores']) / len(x[1]['quality_scores'])) / (sum(x[1]['costs']) / len(x[1]['costs']) * 1000))
    
    print("🏆 RECOMMENDATIONS:\n")
    print(f"   Best Quality: {best_quality[0]}")
    print(f"   Best Value: {best_value[0]}")


def save_evaluation_results(all_scores: List[Dict], output_path: Path):
    """Save evaluation results to JSON"""
    
    # Convert QualityScore objects to dicts
    serializable_scores = []
    for item in all_scores:
        scores_dict = {
            'model': item['model'],
            'transcript_id': item['transcript_id'],
            'cost': item['cost'],
            'response_time': item['response_time'],
            'quality_scores': {
                'learning_objective_clarity': item['scores'].learning_objective_clarity,
                'proof_appropriateness': item['scores'].proof_appropriateness,
                'solution_accuracy': item['scores'].solution_accuracy,
                'solution_clarity': item['scores'].solution_clarity,
                'misconception_relevance': item['scores'].misconception_relevance,
                'difficulty_alignment': item['scores'].difficulty_alignment,
                'pedagogical_tone': item['scores'].pedagogical_tone,
                'total_score': item['scores'].total_score,
                'percentage': item['scores'].percentage
            }
        }
        serializable_scores.append(scores_dict)
    
    with open(output_path, 'w') as f:
        json.dump(serializable_scores, f, indent=2)
    
    print(f"\n✅ Evaluation saved to: {output_path}\n")


if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="Evaluate quality of LLM-generated exercises")
    parser.add_argument("--results", type=Path, required=True, help="Path to llm_comparison_results.json")
    
    args = parser.parse_args()
    
    if not args.results.exists():
        print(f"❌ Results file not found: {args.results}")
        sys.exit(1)
    
    try:
        evaluate_results(args.results)
    except KeyboardInterrupt:
        print("\n\n⚠️  Evaluation interrupted. Partial results may have been saved.")
        sys.exit(0)
